using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EnemySpawner : MonoBehaviour
{

    [SerializeField] private List<WaveConfig> waveConfigs;
    private int startingWave = 0;

    // Start is called before the first frame update
    void Start()
    {
        var currentWave = waveConfigs[startingWave];
        StartCoroutine(SpawnWaveEnemies(currentWave));
    }


    // Update is called once per frame
    void Update()
    {
        
    }

    private IEnumerator SpawnWaveEnemies(WaveConfig waveConfig)
    {
        for (int enemyCount = 0; enemyCount < waveConfig.GetNumberOfEnemies(); enemyCount++)
        {
            Instantiate(
                waveConfig.GetEnemyPrefab(),
                waveConfig.GetWaypoints()[enemyCount].position,
                Quaternion.identity);
            yield return new WaitForSeconds(
                waveConfig.GetTimeBetweenSpawns() + 
                UnityEngine.Random.Range(
                    -waveConfig.GetSpawnRandomFactor(), 
                    waveConfig.GetSpawnRandomFactor()
                    )
                ); 
        }
    }
}
